migrate contributing docs to core
localstack/localstack pull request #10775
Opened 2024-05-06 17:33 UTC by HarshCasper

2024-05-07 07:20 UTC, alexrashed requested changes
Thanks a lot @HarshCasper for jumping on this! Imho moving the contribution guide right to the code was long overdue! 🦸🏽 🚀 
I found a few things which need to be addressed after migrating from Hugo to GitHub markdown, but basically all just very small adjustments and comments necessary.
Afterwards this (and the associated Docs PR https://github.com/localstack/docs/pull/1248) can be merged! 🚀

2024-05-07 07:20 UTC, alexrashed commented on docs/README.md
> +- [Development Environment Setup](development-environment-setup.md)
I think the order should be changed here a little bit, and the first link should be our contribution guidelines:
```suggestion
- [Contribution Guidelines](contributing.md)
- [Development Environment Setup](development-environment-setup.md)
- [LocalStack Concepts](Concepts/index.md)
```

2024-05-07 07:20 UTC, alexrashed commented on docs/development-environment-setup.md
> +{{< youtube XHLBy6VKuCM >}}
Here is a Hugo shortcode, and there are at least 13 others like this (looking for `{{<`).

2024-05-07 07:20 UTC, alexrashed commented on docs/Concepts/index.md
> +These resources are not hidden behind the service API, and need to be exposed through an available network port. This is what the [external service port range](https://docs.localstack.cloud/localstac
This link is broken:
```suggestion
These resources are not hidden behind the service API, and need to be exposed through an available network port. This is what the [external service port range](https://docs.localstack.cloud/references/external-ports/) is for. We expose this port range by default in the docker-compose template, or via the CLI.
```

Would also be great to have one line per sentence in this file for easier reviewing and diffing. 😋

2024-05-07 07:20 UTC, alexrashed commented on docs/Concepts/index.md
> +Some handlers are designed to be extended dynamically at runtime by other services. For example, a service can add HTTP routes to the edge router, which can then process the request differently. Open
This link is broken:
```suggestion
Some handlers are designed to be extended dynamically at runtime by other services. For example, a service can add HTTP routes to the edge router, which can then process the request differently. OpenSearch, for example, uses this to register HTTP routes to [cluster endpoints](https://docs.localstack.cloud/user-guide/aws/opensearch/#interact-with-the-cluster), that are proxied through `:4566` to the cluster backend.
```

2024-05-07 07:20 UTC, alexrashed commented on docs/Concepts/index.md
> +    ...
I don't know what this is, but the three dots cause some weird UI changes which are visible not only in the PR diff, but also in the rendered markdown. I think this (and other occurrences) should be changed for better rendering.

2024-05-07 07:20 UTC, alexrashed commented on docs/parity-testing.md
> +```json
This isn't json, which (I guess) breaks the rendering here in a weird way:
![image](https://github.com/localstack/localstack/assets/2796604/cc4b226a-e050-44d0-8f50-ed7ed89e787b)

2024-05-07 07:20 UTC, alexrashed commented on docs/multi-account-region-testing.md
> +![CircleCI Trigger Pipeline](../randomize-aws-credentials.png)
This link seems to be broken.
```suggestion
![CircleCI Trigger Pipeline](./randomize-aws-credentials.png)
```

2024-05-07 07:38 UTC, alexrashed commented on docs/contributing.md
Quick PS because I just stumbled about a few things concerning this file:
- There is still the contribution guidelines in the root of the repo: https://github.com/localstack/localstack/blob/master/CONTRIBUTING.md
  - I think they should be merged.
- I think it is best practice to have this file named `CONTRIBUTING.md` (caps)
- This will be the starting point for the Contribute page of the repo: https://github.com/localstack/localstack/contribute
  - Would it make sense to have the content of the README basically be here and the README just forward to this page (and maybe to the EULA)?

2024-05-07 13:20 UTC, alexrashed commented on CONTRIBUTING.md
> +The guides in this section are for developers of LocalStack, to better understand how LocalStack works internally, how to set up local development environments, and how to contribute to the codebase.
This sentence is a duplicate of the sentence above...

2024-05-07 13:22 UTC, alexrashed commented on docs/Concepts/index.md
> +    ...
Just our of curiosity: Do you know what caused this weird rendering?

2024-05-07 13:40 UTC, alexrashed commented on docs/parity-testing.md
> +This guide assumes you are already familiar with writing [integration tests](integration-tests) for LocalStack in general.
I am pretty sure this link doesn't work as it should have the file ending (but I might be wrong?)...

2024-05-07 13:40 UTC, alexrashed commented on docs/parity-testing.md
> +    * Check out our [Integration Test Guide](integration-tests#running-integration-tests-against-aws) for tips on how run integration tests against AWS.
I am pretty sure this link doesn't work as it should have the file ending (but I might be wrong?)...

2024-05-07 13:41 UTC, alexrashed commented on docs/integration-tests.md
> +Please check our subsequent guide on [Parity Testing](parity-testing) for a detailed explanation on how to write AWS validated snapshot tests.
I am pretty sure this link doesn't work as it should have the file ending (but I might be wrong?)...

2024-05-07 13:42 UTC, alexrashed commented on docs/development-environment-setup.md
> +* Terraform needs version <0.14 to work currently. Use `tfenv` (<https://github.com/tfutils/tfenv>) to manage terraform versions comfortable. Quick start: `tfenv install 0.13.7 && tfenv use 0.13.7`
Here the `tfenv` link seems to be formatted like it should be a linked word, but it's a link in brackets. Is this on purpose?

2024-05-07 16:13 UTC, thrau approved these changes
thanks for addressing all the feedback! i think it looks good for a first iteration.

* can we do consistent lower casing? `Concepts` -> `concepts`

For the future i would suggest
* perhaps adding an index.md to `docs` to outline the localstack internal docs
* changing `CONTRIBUTING.md` to simply say 'we welcome contributions, ... please read the guide here.", i.e. just using it as a gateway and remove all the other text
* only have folders in `docs/`, i.e, move `development-environment-setup.md` to `development-environment-setup/index.md` for consistency

2024-05-07 16:13 UTC, thrau commented on CODEOWNERS
> +/docs/ @HarshCasper
please add me here as well, since i wrote most of it :-)

2024-05-08 07:02 UTC, alexrashed approved these changes
Awesome! Thanks a lot for addressing all the comments! This really looks great now! 🚀 💯

2024-05-08 07:22 UTC, merged