Feature/DynamoDBStreams: decompose process records
localstack/localstack pull request #11821
Opened 2024-11-10 20:58 UTC by maxhoheiser

## Motivation
Decompose function that processes dynamodb records so each individual record can be collected as an event by EventStudio before they are sent to the kinesis stream

2024-11-13 08:00 UTC, giograno requested changes
Changes look harmless 👍 I only have a few minor comments.

2024-11-14 09:01 UTC, maxhoheiser commented on localstack-core/localstack/services/dynamodb/provider.py
> +        "Required for patching submit with local thread context for EventStudio"
fixed in: https://github.com/localstack/localstack/pull/11821/commits/66d704c2c7d8ccf07aee2ca30cc66c9e1e637b12

2024-11-14 10:05 UTC, maxhoheiser commented on localstack-core/localstack/services/dynamodb/provider.py
> +                forwarder=self._forward,
fixed in: https://github.com/localstack/localstack/pull/11821/commits/5bc6ad8324fbaef4d433e37e5cf73b9e5d0a30ef

2024-11-15 08:18 UTC, giograno approved these changes
✔️

2024-11-15 08:28 UTC, merged