Relax healthcheck time constraints
localstack/localstack pull request #12067
Opened 2024-12-23 10:43 UTC by displaylink-kstrzemp

## Motivation

Fix issue: https://github.com/localstack/localstack/issues/11259

## Changes

Relaxed time constraints in healthcheck

2024-12-23 10:58 UTC, displaylink-kstrzemp commented
I have read the CLA Document and I hereby sign the CLA

2025-01-07 08:56 UTC, alexrashed commented
recheck

2025-01-07 13:45 UTC, bentsku requested changes
Thanks a lot for opening a PR and providing a fix for the issue. Looking at the logs of the linked issue, it seems the command was taking around 5.2 seconds to run, leading into the timeout issue. 

I think the `10s` timeout is a good change, as the interval is `10s` anyway. However, diminishing the number of retries might lead to unexpected changes for other users, as before the container had around 15s of start period + 4 interval of 10s + last retry of 5s timeout, and it will now be 15s + 2 interval of 10s + last retry of 10s. 

Would you mind reverting the change of retries and then the PR would be good to merge. Thanks again for your contribution 🙏

2025-01-07 14:08 UTC, displaylink-kstrzemp commented
> Thanks a lot for opening a PR and providing a fix for the issue. Looking at the logs of the linked issue, it seems the command was taking around 5.2 seconds to run, leading into the timeout issue.
> 
> I think the `10s` timeout is a good change, as the interval is `10s` anyway. However, diminishing the number of retries might lead to unexpected changes for other users, as before the container had around 15s of start period + 4 interval of 10s + last retry of 5s timeout, and it will now be 15s + 2 interval of 10s + last retry of 10s.
> 
> Would you mind reverting the change of retries and then the PR would be good to merge. Thanks again for your contribution 🙏

done

2025-01-07 14:22 UTC, bentsku approved these changes
LGTM! Awesome, thanks a lot for being so reactive in pushing the changes. Sorry for the delay in reviewing this PR with the holiday season. Thanks again for your PR, and welcome to the contributors of LocalStack!

2025-01-07 16:31 UTC, merged