Release helm chart
localstack/localstack pull request #3312
Opened 2020-12-06 04:29 UTC by mforutan

Using GitHub Actions to release the official helm chart

This PR is a starting point to introduce an official helm chart for locakstack,

I copied the helm chart from https://github.com/sidhuko/charts/pull/1 without any modification (hope it is fine with @sidhuko)

There are couple of tasks that need to be done before this can be merged:
- A `gh-pages` branch need to be created
- `GitHub Pages` need to be enabled in the setting

TODO (can be done in this PR or next PRs):
- A GitHub workflow to test the helm chart for PRs

Fixes #882

2020-12-06 18:14 UTC, macnev2013 requested changes

2020-12-06 18:14 UTC, macnev2013 commented on chart/localstack/values.yaml
> +      nodePort: 31583
We can remove this except `4566` and `4571`.

2020-12-06 23:23 UTC, sidhuko commented on chart/localstack/values-production.yaml
> +      nodePort: 31583
How about setting <SERVICE>_PORT_EXTERNAL or is this not required anymore?

2020-12-06 23:39 UTC, sidhuko commented
Sorry, been a busy week. I've created a new branch (localstack-chart) to submit as a helm chart on their repository but it needs some work. I am unsure about contributors comments above as it seems we still have `<SERVICE>_PORT_EXTERNAL` and `<SERVICE>_BACKEND`. I am not sure if both are still used? I've supported `<SERVICE>_BACKEND` which can be specified by passing an key value pair under `services` of the new configuration in new branch. If neither are support or will be deprecated it will make it easier. Otherwise I can still expose multiple ports by reverting to what we have here.

We will also need to expose the new environment variables as configuration in the deployment and values file.

2020-12-07 05:01 UTC, macnev2013 commented on chart/localstack/values-production.yaml
> +      nodePort: 31583
Yes, as per my knowledge it is deprecated. We are using single entrypoint for all the services (by default `4566`) and 4571.

Ref. https://github.com/localstack/localstack#announcements
Ref. [docker-compose.yaml](https://github.com/localstack/localstack/blob/master/docker-compose.yml#L8-L10)

2020-12-07 05:07 UTC, macnev2013 commented
> Sorry, been a busy week. I've created a new branch (localstack-chart) to submit as a helm chart on their repository but it needs some work. I am unsure about contributors comments above as it seems we still have `<SERVICE>_PORT_EXTERNAL` and `<SERVICE>_BACKEND`. I am not sure if both are still used? I've supported `<SERVICE>_BACKEND` which can be specified by passing an key value pair under `services` of the new configuration in new branch. If neither are support or will be deprecated it will make it easier. Otherwise I can still expose multiple ports by reverting to what we have here.

Hey @sidhuko, As far as I know we don't use it anymore. @whummer can you confirm it?

2020-12-07 05:10 UTC, macnev2013 commented
> We will also need to expose the new environment variables as configuration in the deployment and values file.

Yes @sidhuko, we need to add new variables as well. For the starting point maybe we can start importing variables present in the compose file.

Ref. [docker-compose.yaml](https://github.com/localstack/localstack/blob/master/docker-compose.yml#L12-L18)

2020-12-07 05:40 UTC, mforutan commented
@macnev2013 @sidhuko, what do you think if we change the chart's version to `0.1.0-beta.0` and merge this PR to have the process of releasing the chart in place then we can fix the rest of issues and release the chart in next PRs, my aim here is to keep these two steps separated so everyone can contribute individually.

2020-12-07 07:43 UTC, whummer commented
Thanks @mforutan for creating the initial chart version 👍 and thanks @macnev2013 @sidhuko for reviewing. Agreed that we can merge this initial version as-is, we'll make a couple of changes and enhancements (e.g., removing the legacy service ports) as we go.. Thanks

2020-12-07 07:46 UTC, merged

2020-12-07 07:53 UTC, mforutan commented
hi @whummer, thank you for merging this PR but it failed to deploy the chart as the `gh-pages` branch wasn't created, can you please do these steps to get the chart deployed?

- Remove the new tag: https://github.com/localstack/localstack/releases/tag/localstack-0.1.0
- Create `gh-pages` branch
- Enable GitHub pages in the setting
- Re-run the GitHub Actions: https://github.com/localstack/localstack/actions/runs/405281754

2020-12-07 08:02 UTC, whummer commented
Thanks @mforutan . Actually, I think we may need to move the chart to a separate repo in that case, or do you know if there is a way to prevent the `helm/chart-releaser-action@v1.1.0` Github action plugin from creating tags (since we're already using tags to create LocalStack code releases)?

2020-12-07 08:22 UTC, mforutan commented
[helm/chart-releaser](https://github.com/helm/chart-releaser) uses GitHub release to store the chart and also to compare it with the existing versions, 

If you are able to create a new repo, I am more than happy to create a new PR against that or we may need to see how to ignore this new tags in code releases.

2020-12-07 13:13 UTC, JamesArthurHolland commented on chart/localstack/templates/NOTES.txt
> +  {{- range $.Values.ingress.paths }}
Error: template: templates/NOTES.txt:4:12: executing "templates/NOTES.txt" at <.paths>: can't evaluate field paths in type interface {}

values.yml - ingress
ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths:
    - /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

2020-12-07 13:16 UTC, JamesArthurHolland commented on chart/localstack/templates/NOTES.txt
> +  {{- range $.Values.ingress.paths }}
The error is there also when paths isn't altered from the PR

2020-12-07 15:44 UTC, JamesArthurHolland commented on chart/localstack/templates/service.yaml
> +      {{- if contains "NodePort" .Values.service.type }}
This creates a scope error:
`Error: template: localstack/templates/service.yaml:28:40: executing "localstack/templates/service.yaml" at <.Values.service.type>: nil pointer evaluating interface {}.service`


I think it should be 
`$.Values.service.type`

2020-12-07 16:01 UTC, sidhuko commented
I cannot say as not a contributor here. It's early Monday morning for me. I
will hopefully complete by end of day today and get the PR across to
helm/charts.

They are quite responsive. Merge in couple days as long as no significant
changes are needed. I will leave notes here so you can try install locally
and test for me. The chart will be better in helm/charts then here for
continued support though.

On Sun, 6 Dec 2020, 10:40 pm Mohammad Forutan, <notifications@github.com>
wrote:

> @macnev2013 <https://github.com/macnev2013> @sidhuko
> <https://github.com/sidhuko>, what do you think if we change the chart's
> version to 0.1.0-beta.0 and merge this PR to have the process of
> releasing the chart in place then we can fix the rest of issues and release
> the chart in next PRs, my aim here is to keep these two steps separated so
> everyone can contribute individually.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/localstack/localstack/pull/3312#issuecomment-739678780>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAVFBWMRJJQXZS6BT6F4FALSTRTFRANCNFSM4UPBHNHA>
> .
>

2020-12-07 16:21 UTC, whummer commented
Thanks all for your inputs - we'll first migrate the chart into a separate repo later today, then we can continue making the incremental changes. Will share the details here shortly. Thanks

2020-12-07 18:24 UTC, whummer commented
@mforutan @sidhuko @macnev2013 @JamesArthurHolland Moved the chart into this new repo: https://github.com/localstack/helm-charts . We'll create the gh-pages branch and the Github actions build shortly.. Thanks

2020-12-07 22:56 UTC, mforutan commented
@whummer Awesome!