Fix the showing of Flask API Logs according to which service is started
localstack/localstack pull request #4250
Opened 2021-07-01 22:20 UTC by pinzon

The starting or not of certain services based on Flask, makes the logs inconsistent, with this PR the quieting of those logs are mostly depended on the DEBUG variable.

I think we should consider removing completly the `quiet` param since just quieting one service, quiets all the other Flask APi's, because they share the **werkzeug** logger.

This PR  addresses #4162

2021-07-02 10:45 UTC, whummer approved these changes
Thanks for this PR @pinzon !

Changes LGTM - asking @thrau to provide his feedback as well.

> I think we should consider removing completly the quiet param since just quieting one service, quiets all the other Flask APi's, because they share the werkzeug logger.

Agreed - we can probably look into removing this parameter mid-term, and rather handle the log verbosity via config options like `DEBUG`. 👍 Thanks

2021-07-02 10:51 UTC, thrau requested changes
thanks for taking a look at this. it's a great catch!

but i agree with your comment. let's remove the quiet parameter all together if possible, and simply consider `config.DEBUG` as the source of truth. i don't think using the absence of a boolean value as a third semantic is a good idea. it essentially gives a boolean three values, which is super confusing.

2021-07-02 10:51 UTC, thrau commented
if you want it merged quickly, then i'd be OK with accepting the current changes and making a follow-up PR.

2021-07-02 21:37 UTC, pinzon commented
Thanks for your comments @thrau and @whummer. I just made a PR removing the parameter. 
I had to force-push for the conficts and because my original commit removed the parameter from other unrelated places.

2021-07-02 23:49 UTC, thrau approved these changes

2021-07-03 00:06 UTC, thrau commented
🤔 can't quite figure out why the build isn't being triggered for this PR

2021-07-03 10:42 UTC, merged

2021-07-03 10:45 UTC, thrau commented
Thanks again for digging into this! Lots of log output now ;-)