Use pre-commit to automatically lint/format files
localstack/localstack pull request #4284
Opened 2021-07-12 06:10 UTC by dominikschubert

This PR adds a pre-commit config to automatically run black/flake8 on commit. 

`pip install -r requirements.txt`
`make init-precommit` or `pre-commit install` will add the hook to `./.git/hooks`

To test it simply change a python file in `tests/` to be incompatible with the back format (e.g. use `'` quotes for a string) and try to commit the changes. It should fail the commit and automatically format the file for you.

2021-07-12 08:57 UTC, thrau requested changes
two things:
* the pre-commit hook does not seem to check/invoke the isort rules. could we also add `isort`?
* and is flake8 using the .flake8 config for checking the rules by default? (see `make lint` target)

2021-07-13 06:44 UTC, dominikschubert commented
@thrau 

> * the pre-commit hook does not seem to check/invoke the isort rules. could we also add `isort`?

:heavy_check_mark:  done

> * and is flake8 using the .flake8 config for checking the rules by default? (see `make lint` target)

Yes, It resolves values by default in `setup.py`, `tox.ini` and `.flake8`.
I've also tested it by introducing a rule violation and then ignoring it in `.flake8`. Was behaving as expected. :+1:

2021-07-13 08:16 UTC, dominikschubert commented
@thrau 

new isort hook now also formats on pre-commit instead only checking/reporting

2021-07-13 08:26 UTC, thrau approved these changes
looks good now, thanks for adding this! :raised_hands:

2021-07-13 08:27 UTC, merged