Use Moto account ID resolver
localstack/localstack pull request #6104
Opened 2022-05-20 09:21 UTC by viren-nadkarni

### Summary

### Tests

### Related
Closes:**Please refer to the contribution guidelines in the README when submitting PRs.**

2022-06-03 10:06 UTC, whummer reviewed
Awesome, this is a massive set of changes, 🚀 big step towards proper account handling and multi-account support - kudos @viren-nadkarni ! 🎉  Did an initial review for now - have a few questions/suggestions.. Happy to discuss in more detail!

2022-06-03 11:12 UTC, thrau commented on localstack/services/events/provider.py
> +from moto.core import get_account_id
this is also the most important change for me!

2022-06-03 11:30 UTC, thrau requested changes
Awesome changes @viren-nadkarni, thanks for grinding through them!

My high-level comments are as Waldemar's
* let's introduce our own **internal abstraction for getting the account id**. i suggest that we implement the same pattern as we introduced in https://github.com/spulec/moto/pull/5098
  - introduce an `account_id_resolver` method that can be patched
  - use that method in our own `get_account_id` method
  - patch `moto.core.account_id_resolver` with our `get_account_id` method

  note how this does not actually wrap moto but rather changes the moto behavior (inversion of control)

* do not by default set the access key id in requests to the account id. rather map requests that have `INTERNAL_AWS_ACCESS_KEY_ID` in their auth info to whatever the `account_id_resolver` returns.

2022-06-03 11:30 UTC, thrau commented on localstack/constants.py
> +HEADER_LOCALSTACK_ACCOUNT_ID = "x-localstack-account-id"
love it!

2022-06-03 11:30 UTC, thrau commented on localstack/services/awslambda/lambda_api.py
> +LAMBDA_TEST_ROLE = "arn:aws:iam::%s:role/lambda-test-role" % get_account_id()
i also think we should not have code in there that resolve the account id on module level, to not give anyone else who sees the code crazy ideas ;-)

2022-06-03 11:30 UTC, thrau commented on localstack/utils/aws/aws_stack.py
> +    access_key = access_key or get_account_id()
i was also going to add the same comment elsewhere. i think we should probably not replace instances of `TEST_AWS_ACCESS_KEY_ID`, but rather have the account id resolver map the `TEST_AWS_ACCESS_KEY_ID` to the account id from the current context.

2022-06-03 11:30 UTC, thrau commented on tests/integration/terraform/provider.tf
> +  access_key                  = "000000000000"
+1

2022-06-06 15:38 UTC, viren-nadkarni commented
> but rather have the account id resolver map the TEST_AWS_ACCESS_KEY_ID to the account id from the current context.

@thrau Is it possible to have variables mapped to functions? Closest is the `@property` decorator but that's not applicable here.

2022-06-15 08:59 UTC, viren-nadkarni commented on tests/integration/terraform/provider.tf
> +  access_key                  = "000000000000"
We now have a basic translation layer which maps the access key `test` to account ID `000000000000`.

This should ensure backward compatilbity and also have no impact on presigned S3 URLS.

2022-06-15 10:23 UTC, viren-nadkarni commented on localstack/utils/aws/aws_stack.py
> +    access_key = access_key or get_account_id()
with [881ce200](https://github.com/localstack/localstack/commit/881ce200e2f7d7d0ef22328ab75340f337e5fc43#diff-c249821a753f15353e8eaf413c9109fee4c2cfcab9df57c6fbf2fb9022270039R900), we now use the original access key ID from the request wherever available

2022-06-15 13:09 UTC, thrau approved these changes
This looks very clean now @viren-nadkarni, great job!

Just one minor nit: it would be great if we could move `accounts.py` into `localstack.aws` and also move the newly introduced hook for patching moto into `accounts.py`.

2022-06-16 08:17 UTC, viren-nadkarni commented on localstack/aws/accounts.py
> +    # For now, we assume the client sends Account ID in Access Key ID field.
Good catch. Fixed in da0ce0ff

2022-06-17 13:18 UTC, merged