CFN Stack timestamps attributes
localstack/localstack pull request #6194
Opened 2022-06-02 23:06 UTC by pinzon

This PR  addresses issue #6038. Due to some difficulties with Commandeer while triaging, I couldn't exactly find out why it still displays a stack with the state "DELETE_COMPLETE", my best guess is that it uses the timestamp attributes `["CreationTime", "DeletionTime", "LastUpdatedTime"]` to determine if the stack should be shown but Localstack does not return the "DeletionTime" or the "LastUpdatedTime".

Changes:
- Set the DeletionTime and LastUpdatedTime attributes accordingly.
- Test to validate the return of the attributes when calling the cfn describe stack function.

2022-06-07 15:27 UTC, dominikschubert requested changes
Nice to see more detailed parity for stack operations :+1: 

Encountered some issues with the test that we should solve before merging but otherwise lgtm

2022-06-07 15:27 UTC, dominikschubert commented on tests/integration/cloudformation/test_cloudformation_stacks.py
> +    bucket_name = "test"
```suggestion
@pytest.mark.aws_validated
def test_stack_time_attributes(cfn_client, deploy_cfn_template):
    bucket_name = f"test-{short_uid()}"
```

Please test this against AWS and add the annotation when validated successfully :+1: 

The bucket_name not being unique leads to issues when deploying on AWS.

2022-06-07 15:27 UTC, dominikschubert commented on tests/integration/cloudformation/test_cloudformation_stacks.py
> +        TemplateBody=load_template_raw("template5.yaml"),
load_template_raw is being outphased

2022-06-08 19:04 UTC, pinzon commented
Hi @dominikschubert, considering your comments, I added a simple stack that has only an ApiGateway.RestApi  and the update only changes the name property. Also the test should have all the suggested changes.

2022-06-23 18:07 UTC, dominikschubert commented
Hi @pinzon ! Please rebase on to latest master then we're good to go :+1: 
Just need to check that we don't break the CI since we had some test fixture refactoring in the meantime!

2022-06-23 22:35 UTC, pinzon commented
hi @dominikschubert , I just rebased the branch. :+1:

2022-06-24 07:13 UTC, dominikschubert approved these changes
LGTM! :+1:

2022-06-24 07:13 UTC, merged