remove `fix_return_consumed_capacity`, fixes #6437
localstack/localstack pull request #6439
Opened 2022-07-12 17:08 UTC by brandonstubbs

`fix_return_consumed_capacity` was added for issue #2049.

This seems to be the cause of issue #6437 and it doesn't solve the problem for issue #2049 from what I can tell.
If `ReturnValues` are not specified it always forces `ReturnConsumedCapacity` as `TOTAL`.

Steps to try reproduce #2049 without success:
```bash
# Create table to repro the issue
awslocal dynamodb create-table \
  --table-name "put-item-response" \
  --billing-mode "PAY_PER_REQUEST" \
  --attribute-definitions \
    AttributeName=pkey,AttributeType=S \
  --key-schema \
    AttributeName=pkey,KeyType=HASH \
  --region eu-west-1

# This works as expected, no values are returned as there is no previous item
awslocal dynamodb put-item \
  --table-name "put-item-response" \
  --item '{"pkey":{"S":"test"}}' \
  --return-values "ALL_OLD"

# This works as expected, the values for the previous item is returned.
awslocal dynamodb put-item \
  --table-name "put-item-response" \
  --item '{"pkey":{"S":"test"},"val":{"S":"foo"}}' \
  --return-values "ALL_OLD"

# Cleanup resources
awslocal dynamodb delete-table \
  --table-name "put-item-response"
```

2022-07-14 10:10 UTC, giograno requested changes
Thanks for your contribution @brandonstubbs 👍 
I did check against AWS and indeed, `ConsumedCapacity` should not be in the response.
Could you please add a simple test to this PR?
Something along this lines
```python
def test_return_values(self, dynamodb, dynamodb_client):
    aws_stack.create_dynamodb_table(
        TEST_DDB_TABLE_NAME, partition_key=PARTITION_KEY, client=dynamodb_client
    )
    table = dynamodb.Table(TEST_DDB_TABLE_NAME)
    item1 = {PARTITION_KEY: "id1"}
    item2 = {PARTITION_KEY: "id1", "data": "foobar"}

    response = table.put_item(Item=item1, ReturnValues="ALL_OLD")
    assert response["ResponseMetadata"]["HTTPStatusCode"] == 200
    assert "Attributes" not in response
    assert "ConsumedCapacity" not in response

    response = table.put_item(Item=item2, ReturnValues="ALL_OLD")
    assert response["ResponseMetadata"]["HTTPStatusCode"] == 200
    assert "ConsumedCapacity" not in response
    assert response["Attributes"] == item1

    # clean up
    table.delete()
```
You can even test it against AWS yourself with the following command:
`TEST_TARGET="AWS_CLOUD" TEST_PATH=" tests/integration/test_dynamodb.py::TestDynamoDB::test_return_values" make test`

Thank you very much!

2022-07-14 14:00 UTC, brandonstubbs commented
@giograno no problem at all, found an existing test for the put item validation and added the additional cases that were missing.

Thank you for the prompt reply, have a great day!

2022-07-14 15:42 UTC, giograno requested changes
Thanks for the changes 👍  Just a minor nitpick in the test.
You can try to run the test against the real AWS (as I explained in a previous comment) and mark the test with `@pytest.mark.aws.validated`. Thanks again 🙏

2022-07-14 15:42 UTC, giograno commented on tests/integration/test_dynamodb.py
> +        assert response["ResponseMetadata"]["HTTPStatusCode"] == 200
nitpick: we are calling the same asserts a bunch of times. To be a bit more concise, you can wrap them in an inner function.

2022-07-14 19:18 UTC, brandonstubbs commented
Simplifies the assertions with a validation function and ran it against real AWS using `TEST_TARGET="AWS_CLOUD"`

2022-07-15 10:28 UTC, giograno reviewed
Nice changes @brandonstubbs 👍  just left a really minor suggestion about naming the helping function :)

2022-07-15 10:28 UTC, giograno commented on tests/integration/test_dynamodb.py
> +        validate_response(response)
```suggestion
        _validate_response(response)
```

2022-07-15 10:28 UTC, giograno commented on tests/integration/test_dynamodb.py
> +        validate_response(response)
```suggestion
        _validate_response(response)
```

2022-07-15 10:28 UTC, giograno commented on tests/integration/test_dynamodb.py
> +        validate_response(response)
```suggestion
        _validate_response(response)
```

2022-07-15 13:55 UTC, merged