Add default logging configuration for state machine
localstack/localstack pull request #6628
Opened 2022-08-09 14:33 UTC by giograno

Should address #6486. 
Passing an empty dictionary as `loggingConfiguration`, while being a valid AWS request, as shown in the ticker messes up with persistence. This PR adds the default configuration as the real AWS.

2022-08-10 09:27 UTC, dominikschubert requested changes
Needs an integration test but otherwise LGTM :+1:

2022-08-10 10:32 UTC, whummer approved these changes
As briefly discussed, mid-term we could consider registering the missing class in our upstream SFn persistence implementation. 👍  But the change LGTM, to unblock our users for now 🚀

2022-08-11 12:48 UTC, dominikschubert approved these changes
minor nit regarding resource leaks in test, otherwise LGTM. Feel free to merge when this is fixed :+1:

2022-08-11 12:48 UTC, dominikschubert commented on tests/integration/test_stepfunctions.py
> +    iam_client.delete_role(RoleName=role_name)
unsafe cleanup

This obv. isn't super critical when running against LocalStack but a test against AWS might leak resources here.

Either fixtures or other safer cleanup strategies should be used instead. A finally block would be ok too but would again need to wrap the individual cleanup statements in a safe way so they don't interfere with each other.

2022-08-11 12:48 UTC, dominikschubert commented on tests/integration/test_stepfunctions.py
> +    assert result["loggingConfiguration"]
```suggestion
```

2022-08-11 15:09 UTC, merged