Fix Lambda Kinesis event filtering
localstack/localstack pull request #6826
Opened 2022-09-06 11:55 UTC by danielpoonwj

### Purpose 

Currently Kinesis data event filtering does not work. This is because the data filters are expected to work on parsed JSON, but currently it's a bytes encoded string.

### Approach

https://docs.aws.amazon.com/lambda/latest/dg/invocation-eventfiltering.html#filtering-streams

We don't always have to check for valid JSON, only if the filter pattern contains data properties
```
Incoming data format: Non-JSON
Filter pattern format for data properties: No filter pattern for data properties
Resulting action: Lambda filters (on the other metadata properties only) based on your filter criteria.
```

If data properties are present but the data cannot be parsed as JSON, it will be dropped.
```
Incoming data format: Non-JSON
Filter pattern format for data properties: Valid JSON
Resulting action: Lambda drops the record.
```

2022-09-06 11:57 UTC, danielpoonwj commented
I have read the CLA Document and I hereby sign the CLA

2022-09-06 11:57 UTC, danielpoonwj commented
recheck

2022-09-26 09:15 UTC, danielpoonwj commented
Hi @dominikschubert @dfangl, could you help review this fix?

2022-09-26 09:37 UTC, dominikschubert requested changes
Thanks for fixing this :+1: 

Since this adds a new feature, could you please add a simple test for this? It's also fine if you have some awscli scripts/commands that you were using when reproducing this issue. I can then create an integration test based on these, so we cover the fix here.

2022-09-26 09:37 UTC, dominikschubert commented on localstack/services/awslambda/lambda_utils.py
> +        for rule in filter["Filters"]:
```suggestion
        for rule in filter.get("Filters", []):
```

for additional safety

2022-10-10 13:56 UTC, danielpoonwj commented
Hi @dominikschubert and @thrau, sorry for the delay. I came up with a simple repo to reproduce the issue as well as to confirm the fix. Instead of using `awscli` to create the resources, I used `serverless` - hope you don't mind.

https://github.com/danielpoonwj/localstack-kinesis-filtering-demo

2023-11-23 08:50 UTC, dominikschubert commented
Hi @danielpoonwj!

First, sorry for the delay here. I'd like to help out now finally getting this over the line, but I will need to make some adjustments to the PR here. Could you maybe grant us access to the PR/fork so we can directly contribute?

You can find instructions on how to do this for your fork here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

The required option should be called `Allow edits from maintainers.`

Other than that there won't be anything else to do on your part :+1:

2023-11-23 10:03 UTC, danielpoonwj commented
> Hi @danielpoonwj!
> 
> First, sorry for the delay here. I'd like to help out now finally getting this over the line, but I will need to make some adjustments to the PR here. Could you maybe grant us access to the PR/fork so we can directly contribute?
> 
> You can find instructions on how to do this for your fork here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests
> 
> The required option should be called `Allow edits from maintainers.`
> 
> Other than that there won't be anything else to do on your part 👍

![Screenshot 2023-11-23 at 6 02 25 PM](https://github.com/localstack/localstack/assets/17039704/3dd9b74b-ae6c-4f10-8ca9-edff8a5285c1)

Done thanks you! Let me know if you're able to access it

2023-11-23 16:00 UTC, japuiglaucia commented
Fix Lambda Kinesis event filtering #6826

2023-12-19 19:24 UTC, dominikschubert commented
triggered community integration tests against pro manually @ https://github.com/localstack/localstack/actions/runs/7265552739

2023-12-19 20:27 UTC, dominikschubert approved these changes
Tried to reconcile the changes with latest changes from master. Thanks for your contribution and sorry again that this took a while to get in!

2023-12-19 20:28 UTC, merged