Minor fix for Lambda layer response parsing
localstack/localstack pull request #6935
Opened 2022-09-26 07:26 UTC by whummer

Minor fix for Lambda layer response parsing. Addresses https://github.com/localstack/serverless-localstack/issues/175

Currently, we're taking the incoming `Layers` parameter (which is a list of strings) in the `UpdateFunctionConfiguration` API method, and simply pass it through to the response - however, the response `Layers` attribute should be a list of dicts with the details. 

For now, simply removing `Layers` from the response - it is already being added separately upstream, so this should not break -ext functionality.

---
PR also sneaks in a small fix for `transact_write_items` that surfaced during testing, to raise the correct exception (ASF exception, instead of boto3 error), in order to avoid 500 errors.

2022-09-26 11:32 UTC, dfangl requested changes
The tests fails against pro, as the lambda layer specified will not exist. We should either skip the test, or create a dummy layer and ignore any errors during its creation against community, so the layer would work in pro.

2022-09-27 11:05 UTC, whummer commented
Good catch @dfangl  - added a `@skip_if_pro_enabled` marker, to skip the test in that case.. 👍

2022-09-27 13:06 UTC, whummer commented
Tests are passing (we're still seeing the test timeout, unfortunately..)
```
= 1168 passed, 94 skipped, 32 xfailed, 9 xpassed, 3971 warnings, 2 rerun in 3067.56s (0:51:07) =
```

2022-09-27 13:24 UTC, dfangl approved these changes
Should be fine now! The timeout is unfortunate, it happens more and more often now, it seems pytest hangs on shutdown, should investigate at some point..

2022-09-27 17:41 UTC, merged