send SQS metrics to cloudwatch
localstack/localstack pull request #7182
Opened 2022-11-15 17:10 UTC by steffyP

This PR addresses issue #7131 by sending SQS metrics to cloudwatch.
The metrics are defined in the [AWS docs](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-available-cloudwatch-metrics.html).

Limitations:
* `ApproximateAgeOfOldestMessage` is currently not considered
* Other `Approximate[...]` metrics are scheduled to be send every minute (on AWS the timeframe might be longer, but for LocalStack it probably makes sense to make the metrics available sooner)

2022-11-16 12:04 UTC, thrau requested changes
This looks really cool! Thanks for taking the time to also learn the SQS provider.

I have one larger and one smaller suggestion:
* non-blocking metric publishing so we don't slow down SQS put message operations
* making queue metrics properties of the `SqsQueue` model class

Otherwise code looks :ok_hand:

2022-11-16 12:04 UTC, thrau commented on localstack/services/sqs/provider.py
> +            value=queue.visible._qsize(),
could we add these metrics as attributes to the queue? then we have them in one place! i think we need them in some SQS api calls as well, when we return the queue attributes.

2022-11-16 12:04 UTC, thrau commented on localstack/services/sqs/provider.py
> +            value=len(queue.inflight),
same -> move to queue

2022-11-16 12:04 UTC, thrau commented on localstack/services/sqs/provider.py
> +            value=len(queue.delayed),
same -> move to queue

2022-11-16 12:41 UTC, bentsku commented on localstack/services/sqs/provider.py
> +
The pattern would be a lot simpler I believe, as the metric published/target is always the same. For now, the SNS one is still early draft, but it is going to take a lot of inspiration from the S3 notifications system.

Using the S3 one without the subclassing would be the easiest way to port it for this use case.

2022-11-17 17:06 UTC, thrau approved these changes
awesome! this looks great now. thanks @steffyP ! :shipit:

2022-11-17 17:06 UTC, thrau commented on localstack/services/cloudwatch/provider.py
> +            result["Messages"] = []
parity tests FTW! :100:

2022-11-17 18:08 UTC, steffyP commented
CircleCI has one flaky test `test_transcribe_happy_path` which seems not to be related to the changes of this PR. 
A previous run run all tests successfully, but LocalStack did not shut down correctly (none of the remaining threads was related to the sns-cloudwatch metrics though).
Merging therefore 🤞

2022-11-17 18:18 UTC, merged