support creation of integration responses for apigw method
localstack/localstack pull request #7269
Opened 2022-11-30 21:50 UTC by pinzon

As @calvernaz pointed out. The ApiGW Method wasn't creating correctly the Integration Responses. This PR addresses that.

Changes:

- [x] Refactor the test for the apigateway integration deployment
- [x] Change the template to Yaml for easiear reading

2022-12-02 12:08 UTC, simonrw requested changes
Looks good, but I'm keen to understand why the `integrationResponses` are not being validated

2022-12-02 12:08 UTC, simonrw commented on localstack/services/cloudformation/models/apigateway.py
> +                    del kwargs["integrationResponses"]
nit: could this work? Then you don't have to don't have to check and delete from `kwargs`
```suggestion
                integration_responses = kwargs.pop("integrationResponses", [])
```

2022-12-02 14:23 UTC, pinzon commented on tests/integration/cloudformation/resources/test_apigateway.py
> +        "$..methodIntegration.integrationResponses",
The correct skip_path shoudl be `$..methodIntegration.integrationResponses.200.responseParameters ( {} )` but the snapshot lib crashes using that path. 

the problem is that our ApiGW get_method is not returning in the response the empty responseParameters dict. even though is specified [here](https://github.com/localstack/localstack/blob/e1b478ba738f8b1a7b7195b15d7313f54b7b6baf/localstack/services/cloudformation/models/apigateway.py#L386) 

But yeah this skip can be confusing. I'll add more parameters so we can avoid it.

Thanks for noticing @simonrw

2022-12-05 14:57 UTC, simonrw approved these changes
LGTM! Thanks for addressing my changes :+1:

2022-12-05 19:24 UTC, merged