create a docker-compose pro for licensed users
localstack/localstack pull request #7290
Opened 2022-12-06 06:33 UTC by HarshCasper

## Description

Based on a discussion, this PR proposes two separate files:

- `docker-compose.yml` for community users
- `docker-compose-pro.yml` for licensed users

This PR would also involve a documentation change (which I will take care off).

2022-12-08 09:58 UTC, whummer approved these changes
LGTM 👍 

It's a bit unfortunate that docker-compose does not support conditional statements, otherwise we could have parameterized the image name based on whether the API key is configured or not.

I'm still a bit on the fence whether having a single docker-compose.yml would make sense, and adding a comment to the file that mentions the image name to use for Community/Pro, in the spirit of keeping the number of top-level files limited. But I get the appeal of having it ready and available in the repo, such that users can simply reference `docker-compose -f docker-compose-pro.yml ...`. Not a strong preference, as both solutions seems to be a compromise 🤷

2022-12-10 12:07 UTC, thrau commented on docker-compose.yml
>        - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
we could also remove this?

2022-12-10 12:18 UTC, thrau requested changes
adding to waldemar's comment, i agree that it makes sense to keep the number of top-level files low. but i think having separate files makes sense.

in a second iteration, we could maybe think about adding a separate folder demonstrating different ways of starting localstack, which would include the docker-compose files.

2022-12-10 12:18 UTC, thrau commented on docker-compose.yml
>        - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
guess we could also remove this line

2022-12-10 12:18 UTC, thrau commented on docker-compose.yml
>        - PERSISTENCE=${PERSISTENCE-}
persistence is also a pro feature

2022-12-11 09:14 UTC, merged