fix passing event from default eventbus to custom eventbus
localstack/localstack pull request #7380
Opened 2022-12-21 19:00 UTC by bentsku

This issue arose in a support ticket.

When passing a message from the `default` event bus of EventBridge to a custom one, we would first `json.loads` the event `Details` then pass it down the chain for it to be sent again through `put_events` if the target was an event bus. However, we would not `json.dumps` it again after it being decoded, so we would try to send a `dict` in the `put_event Entries` parameter, which would raise a silent exception. 

The chain is S3 notification -> default EventBridge event bus -> rule on default eventbridge bus -> custom eventbridge bus -> SQS queue. 

```
2022-12-20T23:11:49.182  INFO --- [   asgi_gw_0] l.services.events.provider : Unable to send event notification {'version': '0', 'id': 'a26463c1-9f3e-4e9b-a4f0-0475d478ab9a', 'detail-type': 'Object Created', 'sou... to target {'Arn': 'arn:aws:events:us-west-2:000000000000:event-bus/custom-event-bus', 'Id': 'terraform-20221220230701396700000002', 'RoleArn': 'arn:aws:iam::000000000000:role/service-role/custom-role'}: Parameter validation failed:
Invalid type for parameter Entries[0].Detail, value: {'version': '0', 'bucket': {'name': 'bucket-name'}, 'object': {'key': 'delivery/test.txt', 'size': 212, 'etag': '"ef34c94690f8a66f9e9880c01f6e6818"', 'sequencer': '0062E99A88DC407460'}, 'request-id': 'RKREYG1RN2X92YX6', 'requester': '074255357339', 'source-ip-address': '127.0.0.1', 'reason': 'PutObject'}, type: <class 'dict'>, valid types: <class 'str'>
```

The added test is the sample of the user, taken from Terraform and put into boto3 commands.

2022-12-21 19:54 UTC, bentsku commented on tests/integration/test_events.py
> +        print(received_event)
todo: will need to remove this comment, I'm waiting for the CI run to finish

2022-12-21 20:11 UTC, dominikschubert requested changes
Thanks for fixing this :+1: 

While I agree that the issue/fix is fairly straight forward, it would be nice to have this covered via an `aws_validated` test. :thinking:

2022-12-22 01:08 UTC, bentsku commented
@dominikschubert done! If you can have a look again, it allowed me to sneak another small fix, the `Resources` parameters was not passed and was missing from the snapshot. Hope we can `aws_validate` the other tests as well!

2022-12-22 08:23 UTC, dominikschubert approved these changes
LGTM! :rocket: 

Thanks a lot for adding the validated test :partying_face:

2022-12-22 10:35 UTC, merged