Gather outdated snapshots
localstack/localstack pull request #7739
Opened 2023-02-23 14:07 UTC by baermat

This adds a scripts that enables to gather which snapshots are older than a given date.

2023-02-23 15:43 UTC, baermat commented
Failing tests are unrelated since this doesn't actually affects the code :slightly_smiling_face:

2023-02-23 17:04 UTC, steffyP requested changes
Nice work 🚀 
Finally, we can stop guessing how old the most snapshot tests really are 😄 This will be very helpful for automating the snapshot updates in the future 🤩 

Just one thing I discovered: we have some snapshot-tests "hidden" in subfolders, it would be great if we could also iterate sub directories and search for additional snapshot-files 🙂

2023-02-23 17:04 UTC, steffyP commented on scripts/gather_outdated_snapshots.py
> +    for file in os.listdir(path):
we might need to check sub-folders as well, e.g. for s3 there are some snapshot files in a sub-directory

2023-02-23 21:23 UTC, baermat commented on scripts/gather_outdated_snapshots.py
> +    Example usage: python get_snapshots.py ../tests/integration 24-12-2022
:+1:

2023-02-24 08:14 UTC, steffyP approved these changes
Awesome 🚀 Thanks for the changes @baermat, it will make the snapshot updates much easier 👍

2023-02-24 09:25 UTC, merged