Implement basic persistence for lambda v2
localstack/localstack pull request #7913
Opened 2023-03-20 09:56 UTC by dominikschubert

Adds a first iteration on basic persistence for the new lambda v2 provider.

## Changes

- Start loaded lambda function versions. => This currently only starts functions that were *not* there before. For snapshot-based persistence this doesn't matter but for pods this will ignore "merges" for now.
- Start event source listeners (note: restoring a dynamodbstreams event source mapping is currently broken because the dynamodbstreams provider doesn't properly support persistence yet)

## Discussion
This can obviously be massively extended since we will need to have some diff logic in place for different entities in the service and perform custom restoring procedures depending on what updated. Alternatively we can simple stop everything and start new but this has a massive overhead and might brick already running integrations (e.g. s3 bucket notifications that target a lambda, etc.)

@giograno  What do you think would be the best approach here? Doing a full "runtime reset" on every `on_before_state_load` ? :thinking:

2023-03-20 16:41 UTC, dfangl requested changes
It seems only "light" merging on a per service state is available now, so we need to shutdown the lambda service in `before_state_load` and then start it up in `after_state_load`.

2023-03-20 16:41 UTC, dfangl commented on localstack/services/awslambda/provider.py
> +                                )
It seems like this should be independent from the function? Maybe wrong intendation?

2023-03-21 08:42 UTC, joe4dev approved these changes
Lambda persistence tests from branch `lambda-persistence-tests` succeed on macOS `tests.persistence.services.test_lambda` 👍

2023-03-21 08:42 UTC, joe4dev commented on localstack/services/awslambda/provider.py
> +                            new_config = dataclasses.replace(fn_version.config, state=new_state)
minor side-effect: might create a new `revision_id` because the state is included in the model

2023-03-21 15:01 UTC, merged