fix: Adding validation on kms plaintext based on the key type
localstack/localstack pull request #8103
Opened 2023-04-09 23:55 UTC by jcanabarro

Issue was partially fixed here #8083, but I also need to check the context based on the key type, not only the max allowed plaintext size.
* Added method to validate the plaintext size based on the key type, all those extracted numbers from [boto3 documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/kms/client/encrypt.html)
* Add tests cases to the written function

2023-04-10 11:52 UTC, jcanabarro commented
I have read the CLA Document and I hereby sign the CLA

2023-04-10 11:56 UTC, jcanabarro commented
recheck

2023-04-10 11:57 UTC, jcanabarro commented
recheck

2023-04-11 08:35 UTC, viren-nadkarni commented
@jcanabarro Some of your earlier commits are associated with `joao@querylayer.com`. Could you squash/amend all you commits and use `joaovictorcana@gmail.com` for all the commits?

2023-04-11 09:22 UTC, sannya-singal commented on localstack/services/kms/provider.py
> +        if key.metadata["KeySpec"] == "RSA_2048" and encryption_algorithm == "RSAES_OAEP_SHA_1":
We can use the key spec values from https://github.com/localstack/localstack/blob/ed7e02f18253e22780131cf961304aa9e9df5c85/localstack/aws/api/kms/__init__.py#L158 and for encryption algorithm https://github.com/localstack/localstack/blob/ed7e02f18253e22780131cf961304aa9e9df5c85/localstack/aws/api/kms/__init__.py#L122.

2023-04-11 09:24 UTC, sannya-singal commented on tests/integration/test_kms.py
> +    @pytest.mark.parametrize(
We can add `pytest.mark.aws_validated` handler if it tested against AWS.

2023-04-11 09:25 UTC, sannya-singal requested changes
Thanks for adding this validation 🎉.

2023-04-11 12:11 UTC, jcanabarro commented
@sannya-singal I'll abandon the PR and recreate because even with the rebase I'm still facing issues with the CLA.

2023-04-11 12:11 UTC, closed without merging