Add SourceArn for Events Message Publisher
localstack/localstack pull request #8217
Opened 2023-04-27 19:42 UTC by pinzon

This PR makes the Events service provider pass the RuleArn to the send_event_to_target function. Now the function can put the currect value on the request metadata for the new internal clients.

2023-05-03 16:12 UTC, dfangl requested changes
Just some minor nits.
I think it would be nice to have some tests for the "Scheduled events now handle alternate event buses" part of the PR though, which seems like a great addition/fix!

2023-05-03 16:12 UTC, dfangl commented on localstack/services/events/provider.py
> +                    [target.update({"RuleArn": rule.arn}) or target for target in rule_targets]
Might be easier to use dict unions (https://peps.python.org/pep-0584/) here to achieve this, at first I did not quite get what this is supposed to mean here :)

2023-05-03 18:50 UTC, pinzon commented
@dfangl. while writing the test for alternate event buses I learnt that [scheduled expressions are not supported by buses other than the default](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-create-rule-schedule.html).

2023-05-04 11:15 UTC, dfangl approved these changes
LGTM! Thanks for verifying the changes for scheduled rules. The test failures are fixed by #8251, so no reason to hold back the merge.

2023-05-04 15:01 UTC, merged