KMS: Remove the reserved key value pair from aad
localstack/localstack pull request #8350
Opened 2023-05-23 07:51 UTC by sannya-singal

Issue: `test_encrypt_via_aws_encryption_sdk` in localstack-ext repo invokes `aws_encryption_sdk` which internally updates encryption context param value by the method `_generate_signing_key_and_update_encryption_context` which is done after the actual encryption. Now, when we decrypt this cipher text, we have an additional reserved key-value pair of `encryption_context` by the name `aws-crypto-public-key` which was missing during encryption.

The PR removes the check of any such reserved key-value pair during decryption as no such value is passed for authentication in encryption.

2023-05-23 13:38 UTC, viren-nadkarni reviewed
Deferring to @whummer who has better context :slightly_smiling_face:

2023-05-23 17:08 UTC, whummer requested changes
Kudos for digging into this @sannya-singal , great insights! 🚀 Added a comment regarding the key name (removing the backticks), and a small suggestion for restructuring the code a bit. 👍

2023-05-24 05:46 UTC, sannya-singal commented on localstack/services/kms/models.py
> +            if key != "`aws-crypto-public-key`":
Thanks for the detailed review @whummer 🙏🙂 Doing the restructure and pushing it back again. 
Regarding backticks: My bad, I mistakenly added it in the `defaults.py` of `aws_encryption_sdk` and therefore in `models.py` as well, I am correcting this also.

2023-05-24 09:10 UTC, whummer approved these changes
Thanks for addressing the comments. LGTM! 👍

2023-05-24 09:19 UTC, merged