Limit batch size in delete and change visibility
localstack/localstack pull request #8479
Opened 2023-06-11 12:35 UTC by sinecode

Fix #8478

2023-06-21 17:17 UTC, baermat requested changes
Thank you @sinecode for your contribution, and thank you for the detailed bug report! This already looks very good, I only have a couple of smaller things that need to be addressed, then we can merge this!

2023-06-21 17:20 UTC, baermat commented
I also ran the tests (with the hashtag removed and the PR rebased against master) and it looks all good :+1:

2023-06-24 15:07 UTC, sinecode commented on localstack/services/sqs/provider.py
> +            )
Sorry, that's muscle memory from Ruby 😄

2023-06-24 15:08 UTC, sinecode commented on tests/integration/test_sqs.py
> +        assert len(result_recv) > MAX_NUMBER_OF_MESSAGES
Didn't know about the `retry` function! I just made a small change to be sure to get the right quantity of messages at each iteration:

```
        result_recv = []
        target_size = 2 * MAX_NUMBER_OF_MESSAGES

        def _receive_all_messages():
            result_recv.extend(
                aws_client.sqs.receive_message(
                    QueueUrl=queue_url,
                    MaxNumberOfMessages=min(MAX_NUMBER_OF_MESSAGES, target_size - len(result_recv)),
                )["Messages"]
            )
            assert len(result_recv) == target_size

        retry(_receive_all_messages, retries=7, sleep=0.5)
```

2023-06-30 15:04 UTC, baermat approved these changes
Sorry for the delay, discussed this and it looks good now :+1:
Thank you again for your contribution :slightly_smiling_face:

2023-06-30 15:14 UTC, merged