Type conversion for AWS::OpenSearch::Domain
localstack/localstack pull request #9278
Opened 2023-10-02 19:37 UTC by pinzon

## Motivation
The example from the resource type cdocumentation cannot be deployed in LocalStack due to the lack of some extra type conversions for some parameters.

## Changes
Extra type validations and transformations in the resource provider

## Testing
The added test uses the template from the documentation

2023-10-03 06:40 UTC, alexrashed approved these changes
Thanks a lot for jumping on this! 🦸🏽 💯 
The code is looking fine, but I am missing a bit of context. Could you please link the documentation you are referring to in your PR description? And what was the issue when deploying the cloudformation template? Could you maybe add a description or a bit of logs?

2023-10-03 08:45 UTC, dominikschubert requested changes

2023-10-03 08:45 UTC, dominikschubert commented on tests/aws/services/cloudformation/resources/test_opensearch.py
> +    assert domain["DomainStatus"]["DomainName"] == domain_name
This should probably also test the added access policies on the API-level.
Please add snapshots here. :pray:

2023-10-03 08:45 UTC, dominikschubert commented on tests/aws/templates/opensearch_domain_alternative_types.yml
> +Resources:
```suggestion
# sample from https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opensearchservice-domain.html
Resources:
```

2023-10-03 08:45 UTC, dominikschubert commented on localstack/services/opensearch/resource_providers/aws_opensearchservice_domain.py
> +            if isinstance(ebs_options, dict):
when should this ever not be a dict?

2023-10-03 08:45 UTC, dominikschubert commented on localstack/services/opensearch/resource_providers/aws_opensearchservice_domain.py
> +            if properties.get("AccessPolicies") and isinstance(properties["AccessPolicies"], dict):
can this actually already be a string? don't think we have a test for this right?

2023-10-05 14:59 UTC, pinzon commented
@alexrashed This is the [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opensearchservice-domain.html), it has an example template that cannot be deployed on LocalStack.

```logs
Error applying changes for CloudFormation stack "SampleTestStack2344": Parameter validation failed:
localstack_main  | Invalid type for parameter ClusterConfig.InstanceCount, value: 2, type: <class 'str'>, valid types: <class 'int'>
localstack_main  | Invalid type for parameter ClusterConfig.DedicatedMasterCount, value: 3, type: <class 'str'>, valid types: <class 'int'>
localstack_main  | Invalid type for parameter EBSOptions.Iops, value: 0, type: <class 'str'>, valid types: <class 'int'>
localstack_main  | Invalid type for parameter EBSOptions.VolumeSize, value: 20, type: <class 'str'>, valid types: <class 'int'>
localstack_main  | Invalid type for parameter AccessPolicies, value: {'Version': '2012-10-17', 'Statement': [{'Effect': 'Allow', 'Principal': {'AWS': 'arn:aws:iam::123456789012:user/opensearch-user'}, 'Action': 'es:*', 'Resource': 'arn:aws:es:us-east-1:846973539254:domain/test/*'}]}, type: <class 'dict'>, valid types: <class 'str'> 
```

2023-10-05 17:21 UTC, merged