Implement resource provider for AWS::Lambda::Function
localstack/localstack pull request #9321
Opened 2023-10-09 14:03 UTC by dominikschubert

## Motivation

Part of the ongoing effort to migrate to `ResourceProvider` based resources.

Normally we'd add the whole service in a single PR but since the lambda function is pretty big in itself, I thought it makes more sense to introduce this separately.

## Changes

- Introduces a new resource provider for `AWS::Lambda::Function`. (Partially based on work from @joe4dev  in https://github.com/localstack/localstack/pull/8406)
- Adds support for cfnresponse module in python functions (used for simple custom resource communication). See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html
- Improve support for cfn-response module in NodeJS functions (proper locations for `cfn-response.js` files and optional detection)
- Support for idempotent delete on a function

2023-10-09 14:23 UTC, dominikschubert commented on localstack/services/awslambda/resource_providers/aws_lambda_function.py
> +from localstack.utils.testutil import create_zip_file
it's not very urgent but at some point these need to be inlined or included in `localstack.services.cloudformation.provider_utils`

2023-10-09 18:10 UTC, pinzon approved these changes
LGTM

2023-10-17 12:04 UTC, dfangl approved these changes
LGTM! Just one question for understanding.

2023-10-17 12:04 UTC, dfangl commented on localstack/services/awslambda/resource_providers/aws_lambda_function.py
> +    def create(
Do I understand correctly that this is called repeatedly as long as the resource creation is in progress, which acts as a waiter of sorts?

2023-12-04 16:20 UTC, simonrw commented
We will need to include the `DeadLetterConfig` parameter: https://github.com/localstack/localstack/pull/9773

2023-12-18 17:22 UTC, Morijarti requested changes

2023-12-18 17:22 UTC, Morijarti commented on localstack/services/awslambda/resource_providers/aws_lambda_function.py
> +                    "MemorySize",
After selection timeout and MemorySize need to be converted to int if they aren't already

2023-12-18 17:22 UTC, Morijarti commented on localstack/services/awslambda/resource_providers/aws_lambda_function.py
> +            update_config_props["Timeout"] = int(update_config_props["Timeout"])
Same conversion should be done for MemorySize

2024-01-11 18:09 UTC, Morijarti approved these changes

2024-01-12 07:57 UTC, merged