apigateway-kinesis: add region and account id params
localstack/localstack pull request #9595
Opened 2023-11-10 07:48 UTC by sannya-singal

## Motivation
The purpose of this PR is to enhance the stability of apigateway's integration with kinesis when dealing with multi-accounts and multi-regions. The main issue addressed is that when connecting api gateway to kinesis, the `apigateway` client was being instantiated without an `aws_access_key_id`. This omission caused the `kinesis` to be associated with an incorrect account.

## Changes
This PR introduces the use of `region` and `account_id` as mandatory fields in order to connect with the correct `apigateway` client `connect_to` method. The remaining modifications involve propagating the values to the relevant functions.

2023-11-10 11:16 UTC, bentsku requested changes
I don't think we should ever call `connect_to` in our tests? Isn't it what our fixtures are for? I think we could use the `aws_client_factory` instead.

2023-11-10 14:12 UTC, sannya-singal commented
> edit: I see the test is using `resource_util`, maybe that's where the `connect_to` call comes from, as it's what used in it? Still, I believe in tests we should use our fixture, would make the migration for the test to be validated easier.

The `connect_to` call is being used by a helper function `connect_api_gateway_to_kinesis` which is called by the `test_api_gateway_kinesis_integration`. I see similar helper functions eg: `connect_api_gateway_to_sqs` using  `connect_to` call for client, @bentsku 🤔.

2023-11-10 14:16 UTC, bentsku commented
I understand, but I still don't think we should explicitly call `connect_to` in a test? These used in the `helpers` should be only used for internal calls, not during test I would say. We will need to refactor the `connect_api_gateway_to_sqs` as well to be able to validate them against AWS. None of those SQS are validated either. Is there a specific reason to use `connect_to`, doesn't the fixture work?

2023-11-10 14:26 UTC, viren-nadkarni commented
@bentsku is correct, `connect_to()` must not be used in tests. For exceptional uses, we have `connect_externally_to()` which may be used in tests.

@sannya-singal: The proper way will be to pass the `aws_client.apigateway` client instance to `connect_api_gateway_to_kinesis()`

2023-11-10 14:56 UTC, sannya-singal commented
Thanks for pointing this out @bentsku. I have made the required changes using `aws_client_factory` for apigateway client for a specific region and account. Please let me know if there is anything else. 

Also will refactor `connect_api_gateway_to_sqs` in the later PR's. 👍

2023-11-10 15:58 UTC, bentsku approved these changes
Awesome, thanks for fixing it! 🚀

2023-11-11 07:16 UTC, sannya-singal commented
LocalStack-ext test suite run: https://github.com/localstack/localstack-ext/actions/runs/6826365794

2023-11-11 07:16 UTC, merged