CW v2 Tests and small improvements
localstack/localstack pull request #9719
Opened 2023-11-23 18:09 UTC by pinzon

## Motivation

## Changes
- [ ] **Missing Tests + Test improvements**:
  - [x] add pagination tests 
  - [ ] add snapshots to the existing tests
  - [ ] remove the `time.sleep` from the tests and replace with `retry` or other utility
  - [ ] add a test where we try to insert single + static values at the same time (in one put-metric-data statement (probably will throw an error, but we need to test)
  
- [ ] **put-metric-data** improvments (follow up #9475):
  - [ ] verify that the default timestamp added to the metrics is UTC time (might be local timestamp?)

2023-12-11 17:08 UTC, steffyP requested changes
Nice work, thanks for the follow-up work and improving the tests 🚀 😄 

There are still a few test failures, also some tests that worked before are now failing for the v2 provider.

* please make sure that you rebase with the `feat/cloudwatch-v2` branch - it seems like you have two additional commits from the original branch, and one commit is missing (last one from last week, that fixed the pipeline)
* some of the new tests are failing for the old providers: make sure to add the skip-flag if needed
* some skips should probably only be added for the v2 provider (added comments in the code)
* I added several inline-comments, suggestions and questions, we can go through it in a 1:1 session if you like

2023-12-12 09:38 UTC, silv-io reviewed
LGTM,Steffy's input is probably more valuable :) 

Just have a small suggestion

2023-12-12 09:38 UTC, silv-io commented on localstack/services/cloudwatch/cloudwatch_database_helper.py
> +    ) -> dict:
We could use a generic `Dict` type here instead of dict, since we know the typing of the keys and the values.

2023-12-12 14:53 UTC, steffyP commented on localstack/services/cloudwatch/provider_v2.py
> +            # TODO: Fix this. AWS sometimes returns the metric name as label, sometimes is metric with stat
-> @baermat will work on that: adding a test and providing a fix

2023-12-12 15:01 UTC, steffyP commented on tests/aws/services/cloudwatch/test_cloudwatch.py
> +    @markers.snapshot.skip_snapshot_verify(paths=["$..Datapoints..Unit"], condition=is_new_provider)
-> @baermat will add a test here :)

2023-12-13 09:12 UTC, steffyP commented
@pinzon: 
The failing unittest + integration tests relating to websocket import error should be fixed on master already (we don't have this commit yet on our feature branches). 
We can ignore this for now, merge this PR first, and then rebase the `feat/cloudwatch-v2` target branch. 

However, there is still one test failing for the v2 provider: `test_put_metric_uses_utc` - it seems like you used your local-time for testing? ;) Maybe you can try setting an explicit timezone?

2023-12-14 09:28 UTC, steffyP reviewed
Thanks for all the updates and rework, @pinzon 🥳 
I still see two tests failing with the old provider, where we need to adapt/add markers for the test. 
Once we have this, it's good to merge!

2023-12-14 09:28 UTC, steffyP commented on tests/aws/services/cloudwatch/test_cloudwatch.py
> +    @markers.snapshot.skip_snapshot_verify(paths=["$..Datapoints..Unit"], condition=is_new_provider)
my bad: this test is failing with the old provider as well, we need the skip for both providers.

2023-12-14 09:28 UTC, steffyP commented on tests/aws/services/cloudwatch/test_cloudwatch.py
> +    def test_get_metric_data_pagination(self, aws_client):
this test is still with the old provider: please add a skip marker

2023-12-14 13:52 UTC, merged