add opensearch 2.10 and 2.11
localstack/localstack pull request #9935
Opened 2023-12-23 17:17 UTC by HarshCasper

Fixes — https://discuss.localstack.cloud/t/opensearch-cdklocal-deploy-failed/674

2023-12-27 08:16 UTC, viren-nadkarni requested changes
There's a failing test `test_get_compatible_versions` which will need a bump.

2023-12-27 08:16 UTC, viren-nadkarni commented on localstack/constants.py
> +OPENSEARCH_DEFAULT_VERSION = "OpenSearch_2.11"
The default version can only be bumped in a major release

2024-01-02 10:42 UTC, alexrashed requested changes
Thanks a lot for pro-actively adding support for the new version of OpenSearch to LocalStack! 🦸🏽 

Actually, the comment by @viren-nadkarni might be based on a misunderstanding. While the last update was right before the major release, we consider non-breaking parity-adjustments as bugfixes which can be merged as patch (if they are small and concise) or as minor (if they are too big / complex). So it would be great if you could change the default version back to your initial change in the `constants.py`.

After addressing the comments, fixing the default version, and when we have a 💚 pipeline, we can move forward and merge this PR! 🚀 

Let me know if you have any questions, I'm happy to assist / help!

2024-01-02 10:42 UTC, alexrashed commented on localstack/services/opensearch/versions.py
> +            "OpenSearch_2.10",
AWS does not list 2.10 in their supported versions:
```
aws --region us-east-1 opensearch list-versions                                                                                                                                                                                                    11:26:20
{
    "Versions": [
        "OpenSearch_2.11",
        "OpenSearch_2.9",
        "OpenSearch_2.7",
        "OpenSearch_2.5",
        "OpenSearch_2.3",
        "OpenSearch_1.3",
        "OpenSearch_1.2",
        "OpenSearch_1.1",
        "OpenSearch_1.0",
        "Elasticsearch_7.10",
        "Elasticsearch_7.9",
        "Elasticsearch_7.8",
        "Elasticsearch_7.7",
        "Elasticsearch_7.4",
        "Elasticsearch_7.1",
        "Elasticsearch_6.8",
        "Elasticsearch_6.7",
        "Elasticsearch_6.5",
        "Elasticsearch_6.4",
        "Elasticsearch_6.3",
        "Elasticsearch_6.2",
        "Elasticsearch_6.0",
        "Elasticsearch_5.6",
        "Elasticsearch_5.5",
        "Elasticsearch_5.3",
        "Elasticsearch_5.1",
        "Elasticsearch_2.3",
        "Elasticsearch_1.5"
    ]
}
```
Please remove 2.10 here and in the rest of the mapping, and generally make sure to verify your changes against AWS.

2024-01-02 10:42 UTC, alexrashed commented on tests/aws/scenario/bookstore/test_bookstore.snapshot.json
> +              "OpenSearch_2.7", "OpenSearch_2.9", "OpenSearch_2.10", "OpenSearch_2.11"
Same as above, please remove `2.10` here as well.

2024-01-02 10:42 UTC, alexrashed commented on tests/aws/services/es/test_es.py
> +        assert len(versions) == 26
This will become 25 (after the removal of 2.10).
Please also remove the comment in line 124 stating that 2.9 is the current latest version.

2024-01-02 10:42 UTC, alexrashed commented on localstack/services/opensearch/versions.py
> +    "2.11": "2.11.0",
`2.11.1` has been released on the 30th of November and should be used here.

2024-01-02 10:42 UTC, alexrashed commented on tests/aws/services/opensearch/test_opensearch.py
> +            assert response.json()["version"]["number"] == "2.11.0"
After changing the version to `2.11.1`, this needs to be adjusted.

2024-01-04 10:17 UTC, silv-io approved these changes
Besides the points made already in the other review, LGTM!

2024-01-04 10:17 UTC, silv-io commented on tests/aws/services/opensearch/test_opensearch.py
>          expected_compatible_versions = [
This one also contains 2.10, as mentioned by @alexrashed in other places

2024-01-24 08:06 UTC, alexrashed requested changes
Thanks for addressing all the comments! I only found one small leftover, and the snapshot should be updated by running the test against AWS.
Afterwards we're good to go! 🚀 💯

2024-01-24 08:06 UTC, alexrashed commented on tests/aws/scenario/bookstore/test_bookstore.snapshot.json
> +              "OpenSearch_2.7", "OpenSearch_2.9", "OpenSearch_2.11"
It looks a bit like this snapshot was updated manually, which is an anti-pattern (the whole purpose of the snapshot framework is that we know that the responses from LocalStack look the same as the ones from AWS).
Please update the snapshot against AWS and then validate it against LocalStack.
You can do that easily by running the test against your default profile in AWS with these settings:
- `SNAPSHOT_UPDATE=1`
- `TEST_TARGET=AWS_CLOUD`

2024-02-13 08:15 UTC, alexrashed commented on tests/aws/scenario/bookstore/test_bookstore.snapshot.json
> +              "OpenSearch_2.7", "OpenSearch_2.9", "OpenSearch_2.11"
I updated the snapshot in the latest commit.

2024-02-13 08:17 UTC, alexrashed approved these changes
Thanks for addressing the comments, @HarshCasper.
I performed the last missing step - updating the snapshot - and now we should be good to go! 🚀

2024-02-13 08:59 UTC, viren-nadkarni approved these changes
Great to see this going in LocalStack 3.2!

2024-02-13 09:03 UTC, merged